apiVersion: apps/v1
kind: Deployment
      
metadata:
  name: myfiber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myfiber
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: myfiber
    spec:
      containers:
        - image: localhost:5001/myfiber:v3.0.1
          imagePullPolicy: IfNotPresent
          name: myfiber
          ports:
            - containerPort: 3001
