apiVersion: v1
kind: Service
metadata:
  name: myfiber-lb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 7777
    protocol: TCP
    targetPort: 3001
  externalIPs:
  - 172.20.0.50
  selector:
    app: APP_PLACEHOLDER