apiVersion: apps/v1
kind: Deployment
      
metadata:
  name: APP_PLACEHOLDER
spec:
  replicas: REPLICAS_PLACEHOLDER
  selector:
    matchLabels:
      app: APP_PLACEHOLDER
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: APP_PLACEHOLDER
        srv: level13
    spec:
      containers:
        - image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          name: APP_PLACEHOLDER
          ports:
            - containerPort: 3001
